### ISSUE TITLE
elgg-breadcrumbs layout bug

### ISSUE THREAD

**Issue by PerJensen** [Elgg/community_theme#49]
Something changes in elgg-breadcrumbs layout, so the element is sandwiched. I've posted here, but I do not know which plugin is causing it. Perhaps an admin knows?

Default installation:
![breadcrumb-ok](https://cloud.githubusercontent.com/assets/1220345/7331613/a00ddc1e-eb17-11e4-891f-baa40ed082eb.jpg)

Community:
![breadcrumb-buggy](https://cloud.githubusercontent.com/assets/1220345/7331615/a5b0a098-eb17-11e4-823e-cca8b5f76f2b.jpg)

**Comment by mrclay** [comment]
This has bugged me for a long time. It seems to fix itself in various situations so I assumed it was a browser bug.

**Comment by PerJensen** [comment]
Yea, right now it's perfect :)
