### ISSUE TITLE
Redesign of the Landing page

### ISSUE THREAD

**Issue by rjcalifornia** [Elgg/community_theme#51]
Hi guys!

First time opening an issue. I want to propose a redesign of the landing page of elgg.org

As of right now, it looks dated and not attractive for newcomers. Would you be open to have a new theme for the community? There are several open source projects that can be integrated to improve the whole design of the landing page.

**Comment by jeabakker** [comment]
We're always open to new designs. Make a PR and/or post some screenshots of what you have in mind.

**Comment by rjcalifornia** [comment]
It is a work in progress, but you can take a look here:

https://github.com/rjcalifornia/star-admin-theme

I'm also attaching some links to the screenshots of the new theme. I don't know if I can make a PR since it is a brand new theme.

Screenshots Frontpage:
https://github.com/rjcalifornia/star-admin-theme/blob/master/screenshots/elgg-community-landing-slider.png

https://github.com/rjcalifornia/star-admin-theme/blob/master/screenshots/elgg-community-landing-about.png

https://github.com/rjcalifornia/star-admin-theme/blob/master/screenshots/elgg-community-landing-resources.png

Screenshots Community:

https://github.com/rjcalifornia/star-admin-theme/blob/master/screenshots/elgg-community-activity.png

https://github.com/rjcalifornia/star-admin-theme/blob/master/screenshots/elgg-community-profile.png
